#!/usr/bin/env bash
# Create a 1Password item for all-my-favs with generated secrets,
# then materialize .env.op (a `op://` reference file consumed by `op run`).
#
# Usage:
#   ./scripts/op-bootstrap.sh                     # vault=Homelab, item=all-my-favs
#   VAULT=Personal ITEM=amf-prod ./scripts/op-bootstrap.sh
#
# Idempotent: if the item already exists, secrets are NOT regenerated.
# Always writes .env.op (overwriting any prior copy) so the references stay in sync.

set -euo pipefail

VAULT="${VAULT:-Homelab}"
ITEM="${ITEM:-all-my-favs}"
HOST="${HOST:-favs.kjaymiller.dev}"
PORT="${PORT:-8787}"

ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env.op"

if ! command -v op >/dev/null 2>&1; then
  echo "error: 1Password CLI 'op' not found in PATH" >&2
  exit 1
fi

if ! op account get >/dev/null 2>&1; then
  echo "error: not signed in to 1Password. Run: eval \$(op signin)" >&2
  exit 1
fi

gen_secret() {
  # URL-safe random secret of the requested length (default 32).
  # Uses openssl hex output (A-F0-9) so there's no pipeline → SIGPIPE issue
  # under `set -o pipefail`.
  local n="${1:-32}"
  local out
  out="$(openssl rand -hex "$n")"
  printf '%s' "${out:0:n}"
}

if op item get "$ITEM" --vault "$VAULT" >/dev/null 2>&1; then
  echo "✓ 1Password item '$ITEM' already exists in vault '$VAULT' — leaving secrets alone."
else
  echo "→ creating 1Password item '$ITEM' in vault '$VAULT' with generated secrets…"
  API_KEY="$(gen_secret 40)"
  DB_PASSWORD="$(gen_secret 32)"
  op item create \
    --category="API Credential" \
    --vault="$VAULT" \
    --title="$ITEM" \
    --tags="homelab,all-my-favs" \
    "url[text]=https://${HOST}" \
    "api_key[password]=${API_KEY}" \
    "db_password[password]=${DB_PASSWORD}" \
    >/dev/null
  unset API_KEY DB_PASSWORD
  echo "✓ created."
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/op-bootstrap.sh — references resolved at deploy time via:
#   op run --env-file=.env.op -- docker compose up -d
AMF_API_KEY="op://${VAULT}/${ITEM}/api_key"
AMF_DB_PASSWORD="op://${VAULT}/${ITEM}/db_password"
AMF_PORT="${PORT}"
AMF_COOKIE_SECURE="true"
EOF

echo "✓ wrote $ENV_FILE"
echo
echo "Next:"
echo "  op run --env-file=.env.op -- docker compose up -d --build"
